### ISSUE TITLE
Cannot add text

### ISSUE THREAD

**Issue by yonatonreid** [Treinetic/ImageArtist#21]
`require_once('vendor/autoload.php');

use Treinetic\ImageArtist\lib\Text\TextBox;
use Treinetic\ImageArtist\lib\Text\Color;
use Treinetic\ImageArtist\lib\Text\Font;

$img = new \Treinetic\ImageArtist\lib\Image("image1.jpg");
$nm = new \Treinetic\ImageArtist\lib\Image("circle.png");
$nm->resize(200,200);
$img->merge($nm,0,0);

$textBox = new TextBox(310,40);
$textBox->setColor(Color::getColor(Color::$WHITE));
$textBox->setFont(Font::getFont(Font::$NOTOSERIF_REGULAR));
$textBox->setSize(20);
$textBox->setMargin(2);
$textBox->setText("We Are Team Treinetic");
$img->setTextBox($textBox,($img->getWidth()-$textBox->getWidth())/2,$img->getHeight()* (5/7),true);

$img->dump();
`

Produces

`PHP Fatal error:  Uncaught ImagickException: unable to open image `pango:We Are Team Treinetic': No such file or directory @ error/blob.c/OpenBlob/2701 in /var/www/html/genphoto/vendor/treinetic/imageartist/src/lib/Text/Write/ImagickWritingStrategy.php:56
Stack trace:
#0 /var/www/html/genphoto/vendor/treinetic/imageartist/src/lib/Text/Write/ImagickWritingStrategy.php(56): Imagick->newpseudoimage(310, 40, 'pango:We Are Te...')
#1 /var/www/html/genphoto/vendor/treinetic/imageartist/src/lib/Text/TextWriter.php(49): Treinetic\ImageArtist\lib\Text\Write\ImagickWritingStrategy->write()
#2 /var/www/html/genphoto/vendor/treinetic/imageartist/src/lib/Text/TextWriter.php(43): Treinetic\ImageArtist\lib\Text\TextWriter->getImage()
#3 /var/www/html/genphoto/vendor/treinetic/imageartist/src/lib/Image.php(167): Treinetic\ImageArtist\lib\Text\TextWriter->write(Object(Treinetic\ImageArtist\lib\Image), 145, 428.57142857143)
#4 /var/www/html/genphoto/index.php(21): Treinetic\ImageArtist\lib\Image->setTextBox(Object(Treinetic\ImageArtist\lib\Text in /var/www/html/genphoto/vendor/treinetic/imageartist/src/lib/Text/Write/ImagickWritingStrategy.php on line 56
`

**Comment by Meti27** [comment]
same problem

**Comment by szef0** [comment]
any info? 👍

**Comment by yonatonreid** [comment]
nope. switched to a different library, dont remember which one though lol sorry :(

**Comment by sirion89** [comment]
I resolved this by switching to GD. With gd i had no issue. All you have to do is change this:

$textBox = new TextBox(310,40);

to this:

$textBox = new TextBox(310,40,false);

which disable auto-detect for writer (which internally defaults to imagick as first choice)
